### PR TITLE
fix: Default value for map fields

### LINKED ISSUE #326: [Recommender] Incorrect default parameter generated for some map parameters in testing
when generating Recommender v1beta1 with synth tool (see [Recommender PR 4734 in google-cloud-ruby](https://github.com/googleapis/google-cloud-ruby/pull/4734)):

if we run tests with 
```sh
bundle exec rake ci
```
we get an error like this for some testing methods:

```
Error:                                                   
Google::Cloud::Recommender::V1::Recommender::ClientTest#test_mark_recommendation_succeeded:                                 
ArgumentError: Expected Hash object as initializer value for map field 'state_metadata' (given Array).                      
    /usr/local/google/home/virost/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/gapic-common-0.1.0/lib/gapic/protobuf.rb:38:in `initialize'                                                                                                        
    /usr/local/google/home/virost/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/gapic-common-0.1.0/lib/gapic/protobuf.rb:38:in `new'                                                                                                               
    /usr/local/google/home/virost/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/gapic-common-0.1.0/lib/gapic/protobuf.rb:38:in `coerce'                                                                                                            
    /usr/local/google/home/virost/src/google-cloud-ruby/google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb:394:in `mark_recommendation_succeeded'                                                                        
    /usr/local/google/home/virost/src/google-cloud-ruby/google-cloud-recommender-v1/test/google/cloud/recommender/v1/recommender_test.rb:265:in `block in test_mark_recommendation_succeeded'                                                           
```
in the recommender_test we see:
```ruby
    # Create request parameters for a unary method.
    state_metadata = [{}]
```
and later 

```ruby
# Use hash object
      client.mark_recommendation_succeeded({ name: name, state_metadata: state_metadata, etag: etag }) do |response, operation|
        assert_equal grpc_response, response
        assert_equal grpc_operation, operation
      end
```
where `mark_recommendation_succeeded/1` in the `state_metadata` field of its argument expects a map:

```ruby
 def mark_recommendation_succeeded request, options = nil
              raise ArgumentError, "request must be provided" if request.nil?

              request = Gapic::Protobuf.coerce request, to: Google::Cloud::Recommender::V1::MarkRecommendationSucceededRequest
```
```proto
// Request for the `MarkRecommendationSucceeded` Method.
message MarkRecommendationSucceededRequest {
  // Name of the recommendation.
  string name = 1;

  // State properties to include with this state. Overwrites any existing
  // `state_metadata`.
  map<string, string> state_metadata = 2;

  // Fingerprint of the Recommendation. Provides optimistic locking.
  string etag = 3;
}
```

but it gets invoked with an array.

### PR DESCRIPTION
**Pull request by dazuma**
Fixes #326

### CODE REVIEW

**Comment by quartzmo** [comment]
> In reflection API, map fields will be treated as repeated message fields and each map entry is accessed as a message. This MapEntry class is used to represent these map entry messages in reflection API. 

-- https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MapEntry.html

File: shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb [hunk 1]
```diff
@@ -457,6 +457,8 @@ def get_repeated_garbage request, options = nil
           #     Time limit for this garbage. If not defined, the garbage endures forever.
           #   @param enum [ENUM(GarbageEnum)]
           #     The type of this garbage.
+          #   @param amap [So::Much::Trash::TypicalGarbage::AmapEntry | Hash]
```
Comment (quartzmo) [inline shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb]: I would have expected that given `map :amap, :string, :string, 14` above, the proto type here would be `So::Much::Trash::TypicalGarbage::Amap` or an array of `So::Much::Trash::TypicalGarbage::AmapEntry`, not a single `So::Much::Trash::TypicalGarbage::AmapEntry`. Is there something I am missing?

Comment (dazuma) [reply shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb]: You're right, that type should be an array of AmapEntry since it's repeated underneath. I'll look into why it's not catching that.

Comment (dazuma) [reply shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb]: Well, we have a bigger problem. None of the repeated fields anywhere are documented as `Array`. They're all just documented as the base type. I guess we're fixing more bugs...

Comment (dazuma) [reply shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb]: okay, I've now included a fix for this. It exposed that a _lot_ of the types in our yardocs were incorrect, as indicated by the changes to generated files in this PR.

File: shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb [hunk 2]
```diff
@@ -176,7 +176,7 @@ def get_campaign request, options = nil
               # @overload mutate_campaigns(customer_id: nil, operations: nil, partial_failure: nil, validate_only: nil)
               #   @param customer_id [String]
               #     The ID of the customer whose campaigns are being modified.
-              #   @param operations [Google::Ads::GoogleAds::V1::Services::CampaignOperation | Hash]
+              #   @param operations [Array<Google::Ads::GoogleAds::V1::Services::CampaignOperation | Hash>]
```
Comment (quartzmo) [inline shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb]: `>` for `Array` should follow `Operation`, not `Hash`.

Comment (quartzmo) [reply shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb]: Oh, maybe I'm wrong about that, but still not sure this works with YARD as it is now.

Comment (dazuma) [reply shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb]: Actually, it should follow `Hash` because it's an array of either operation objects or hashes. So that part is correct as is.

But now that you drill into this, I realize there are still things wrong. The yard syntax is to use commas rather than vertical pipes. Also, none of the params under the overload clauses are actually getting rendered in yard to begin with (probably for unrelated reasons that I haven't sussed out yet).

This PR is fast going to turn into a fix-everything-wrong-with-yard PR which I want to avoid. Can we accept this PR which fixes some things but not others, and most importantly unblocks generation of the recommender service? I'll file additional issues for the other bugs we're seeing.

Comment (quartzmo) [reply shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb]: Agreed
